### ISSUE TITLE
Following does not work

### ISSUE THREAD

**Issue by SeveralP** [davidwickerhf/instaclient#13]
`users = ['macrsina', 'campbell_collection', 'ms_francesca_2ya', '_maygouda_', 'is_sticx', 'the.beauty.myth', 'stelarkn', 'glambyjesse', 'la_collective', 'chelseabellwalker', 'kehlanihavanna', 'maiisbellamake', 'aaminaaj', 'shaun.freemann', 'francimyelke', 'theinfringeman20', '__nontobeko', 'chanteljoyxowell', 'moyosore.o', 'mustahsunsunny', 'codenamepink', 'mahdiar_taji', 'chelsthedoll', 'tlongerthomas']

x = 0
while 24>x:
    x += 1
    try:
        profile = client.get_profile(users[x])
        profile.follow()
        print(users[x])
    except:
        pass`
Pretty sure I am doing this the right way but it still does not work, try yourself.

**Comment by davidwickerhf** [comment]
Hi, thank you for posting this issue.
May I ask if you receive any errors?
May you paste the full error you receive?

**Comment by SeveralP** [comment]
> Hi, thank you for posting this issue.
> May I ask if you receive any errors?
> May you paste the full error you receive?

there were no errors, it went to their profile but never followed. Recommend you run the code above
Video of it happening:
https://i.gyazo.com/a04f8c9f1f1f72a4c52b393c44e34866.mp4

**Comment by davidwickerhf** [comment]
Can you check what version of the instaclient are you using?

**Comment by SeveralP** [comment]
Ah, just updated and it worked, was on version 2.8.3. My bad

**Comment by davidwickerhf** [comment]
No worries👍 I'm glad it works fine.
