### ISSUE TITLE
Headless seems to be not working

### ISSUE THREAD

**Issue by mv-debug** [davidwickerhf/instaclient#15]
Hi, 

at first, great job! 

Does the headless mode working on your machines? I am on ubuntu 18.04 and the application stucks w/ headless mode on. Further it seems without headless mode the chrome browser needed to be focused to let the app run. Maybe that it a chrome driver thing. I want to put the app into docker by under this condition it is not possible. I only had experience with the gecko driver which worked like a charm.

**Comment by mv-debug** [comment]
It was an issue on my side. The library does everything well.

**Comment by davidwickerhf** [comment]
@mv-debug Mmh that's strange
I don't have Linux so I can't test that unfortunately
On windows it should work as the following:

With `localhost_headless` set to False, the chrome window will pop up. If should work if the window is focused or even if it is not.

With `localhost_headless` set to True, the chrome window will not pop up, though you might see a few more logs by the chrome driver.

The driver I have tested so far is the chromedriver, working with Chrome.

Also try to check your chrome version and your chromedriver version, as they must match - else the driver won't work

**Comment by mv-debug** [comment]
> @mv-debug Mmh that's strange
> I don't have Linux so I can't test that unfortunately
> On windows it should work as the following:
> 
> With `localhost_headless` set to False, the chrome window will pop up. If should work if the window is focused or even if it is not.
> 
> With `localhost_headless` set to True, the chrome window will not pop up, though you might see a few more logs by the chrome driver.
> 
> The driver I have tested so far is the chromedriver, working with Chrome.
> 
> Also try to check your chrome version and your chromedriver version, as they must match - else the driver won't work

As I say everything is okay with the library. I was able to put it into docker. Would you like that I share my code, if you are interested I would like.

**Comment by davidwickerhf** [comment]
> > @mv-debug Mmh that's strange
> > I don't have Linux so I can't test that unfortunately
> > On windows it should work as the following:
> > 
> > With `localhost_headless` set to False, the chrome window will pop up. If should work if the window is focused or even if it is not.
> > 
> > With `localhost_headless` set to True, the chrome window will not pop up, though you might see a few more logs by the chrome driver.
> > 
> > The driver I have tested so far is the chromedriver, working with Chrome.
> > 
> > Also try to check your chrome version and your chromedriver version, as they must match - else the driver won't work
> 
> As I say everything is okay with the library. I was able to put it into docker. Would you like that I share my code, if you are interested I would like.


Sure yes, would you have a GitHub repo? I could make a Wiki Page on the repository for working bot examples
