### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tonweak** [davidwickerhf/instaclient#25]
Hi,

I do not know how to fix this. I've tried different methods but no luck. I am using Windows 10 Enterprise version 20H2.

Here is the error:

raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable

**Comment by davidwickerhf** [comment]
Hi @nullvoid18 ,
sorry for the incredibly late response.
It would seem you don't have Chrome installed (or it is installed in an unusual location) on your machine.
I would suggest either install it, if you haven't already, or uninstalling it and re-install it in the default location.
