### ISSUE TITLE
Client stuck after infinite scorlling

### ISSUE THREAD

**Issue by MayThirtyOne** [davidwickerhf/instaclient#8]
Thank you for this great initiative. I tried the bot today, and it seems to be stuck after infinite loading until the end of the followers list.

Here's what I am trying to achieve.

followers = client.scrape_followers(user='user_name',  count=150, callback_frequency=15) 
print(followers)

For some reason, it never prints the followers list. It's just stuck

**Comment by davidwickerhf** [comment]
Hi, thank you for creating the issue and sorry for the super late reply!
I tried looking into the issue and I believe I managed to find a solution.

you can upgrade to **InstaClient v2.3** () with `pip install -U instaclient`
 v2.3 contains the following changes which you must pay attention to:

- Renamed `check_notifications()` to [`get_notifications()`](https://github.com/wickerdevs/instaclient/blob/main/instaclient/client/instaclient.py#L809)
- Renamed `scrape_followers()` to [`get_followers()`](https://github.com/wickerdevs/instaclient/blob/3318761724f461f66dd9f41ea4c1d332f13034e2/instaclient/client/instaclient.py#L688)
- Method `get_followers()` now allows specifying the number of followers to scrape. Improved speed of this method. It now takes it about 0.6 seconds per follower.
- You can now send DMs also to private accounts (via send_dm() ) 

Notices:
- `BaseProfile.from_username()`  does not work correctly yet as Instagram keeps returning a 429 request code error. I'm working on solving that.

I hope this solves your issue. Again, I'm so sorry for the late reply.
